pipeline{
    agent any
	tools {
		maven 'Maven352'
	}
	stages{
		stage('Checkout'){
			steps {
				git 'https://github.com/shaktipp/testrepo.git'
			}			
		}
		stage('Build') {
			steps {
				sh './DmpMathApp/mvn clean compile'
			}					
		}
		stage('Test') {
			steps {
				sh './DmpMathApp/mvn test'
				junit '**/target/surefire-reports/TEST-*.xml'
				archive 'target/*.jar'
			}
		}
		stage('Package') {
			steps {
				sh './DmpMathApp/mvn package'
			}
		}
		
		stage('Sonar Scan') {
			steps {
				sh './DmpMathApp/mvn sonar:sonar'
			}
		}
		
	}
}